use std::collections::{HashMap, HashSet};
use std::io::Write;
use std::path::{Path, PathBuf};

use tracing::warn;

use crate::decrypt::{CookieData, DecryptedData};

#[derive(Debug, thiserror::Error)]
pub enum WriteError {
    #[error("IO error: {0}")]
    IoError(#[from] std::io::Error),
}

fn cookie_to_netscape(cookie: &CookieData) -> String {
    let domain = &cookie.domain;
    let include_sub = if domain.starts_with('.') {
        "TRUE"
    } else {
        "FALSE"
    };
    let path = cookie.path.as_deref().unwrap_or("/");
    let secure = if cookie.secure.unwrap_or(false) {
        "TRUE"
    } else {
        "FALSE"
    };
    let expiry = cookie.expiration_date.unwrap_or(0.0) as u64;
    let name = &cookie.name;
    let value = &cookie.value;
    format!("{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
}

fn write_netscape_to_writer<W: Write>(
    data: &DecryptedData,
    writer: &mut W,
) -> Result<(), WriteError> {
    writeln!(writer, "# Netscape HTTP Cookie File")?;
    writeln!(writer, "# https://curl.se/docs/http-cookies.html")?;
    writeln!(writer, "# Generated by cookiecloud-sync")?;

    let mut domains: Vec<&String> = data.cookie_data.keys().collect();
    domains.sort();

    for domain in domains {
        if let Some(cookies) = data.cookie_data.get(domain) {
            for cookie in cookies {
                writeln!(writer, "{}", cookie_to_netscape(cookie))?;
            }
        }
    }

    writer.flush()?;
    Ok(())
}

pub fn write_netscape(data: &DecryptedData, path: &Path) -> Result<(), WriteError> {
    let tmp = PathBuf::from(format!("{}.tmp", path.display()));
    {
        let mut file = std::fs::File::create(&tmp)?;
        write_netscape_to_writer(data, &mut file)?;
    }
    std::fs::rename(&tmp, path)?;
    Ok(())
}

pub fn write_json(data: &DecryptedData, path: &Path) -> Result<(), WriteError> {
    let tmp = PathBuf::from(format!("{}.tmp", path.display()));
    let json = serde_json::to_string_pretty(data)
        .map_err(|e| WriteError::IoError(std::io::Error::other(e.to_string())))?;
    std::fs::write(&tmp, &json)?;
    std::fs::rename(&tmp, path)?;
    Ok(())
}

pub fn filter_domains(data: &DecryptedData, domains: &HashSet<String>) -> DecryptedData {
    let normalized_domains: HashSet<String> = domains
        .iter()
        .map(|d| d.trim_start_matches('.').to_lowercase())
        .collect();
    let mut cookie_data: HashMap<String, Vec<CookieData>> = HashMap::new();

    for (domain, cookies) in &data.cookie_data {
        if normalized_domains.contains(&domain.trim_start_matches('.').to_lowercase()) {
            cookie_data.insert(domain.clone(), cookies.clone());
        }
    }

    if cookie_data.is_empty() {
        warn!(
            requested_domains = ?domains,
            available_domains = ?data.cookie_data.keys().collect::<Vec<_>>(),
            "filter_domains: no matching domains found"
        );
    }

    DecryptedData {
        cookie_data,
        local_storage_data: data.local_storage_data.clone(),
        update_time: data.update_time.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::decrypt::CookieData;

    fn test_data() -> DecryptedData {
        let mut cookie_data: HashMap<String, Vec<CookieData>> = HashMap::new();
        cookie_data.insert(
            ".example.com".to_string(),
            vec![CookieData {
                domain: ".example.com".to_string(),
                name: "session".to_string(),
                value: "abc".to_string(),
                path: Some("/".to_string()),
                secure: Some(true),
                http_only: Some(true),
                same_site: Some("Lax".to_string()),
                expiration_date: Some(9999999999.0),
            }],
        );
        cookie_data.insert(
            "github.com".to_string(),
            vec![CookieData {
                domain: "github.com".to_string(),
                name: "token".to_string(),
                value: "xyz".to_string(),
                path: Some("/".to_string()),
                secure: Some(true),
                http_only: Some(true),
                same_site: Some("Strict".to_string()),
                expiration_date: Some(9999999999.0),
            }],
        );
        DecryptedData {
            cookie_data,
            local_storage_data: None,
            update_time: Some("2026-01-01T00:00:00Z".to_string()),
        }
    }

    #[test]
    fn test_filter_single_domain() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert(".example.com".to_string());

        let filtered = filter_domains(&data, &domains);
        assert_eq!(filtered.cookie_data.len(), 1);
        assert!(filtered.cookie_data.contains_key(".example.com"));
        assert!(!filtered.cookie_data.contains_key("github.com"));
    }

    #[test]
    fn test_filter_multiple_domains() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert(".example.com".to_string());
        domains.insert("github.com".to_string());

        let filtered = filter_domains(&data, &domains);
        assert_eq!(filtered.cookie_data.len(), 2);
    }

    #[test]
    fn test_filter_no_match() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert("nonexistent.com".to_string());

        let filtered = filter_domains(&data, &domains);
        assert!(filtered.cookie_data.is_empty());
    }

    #[test]
    fn test_filter_case_insensitive() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert(".EXAMPLE.COM".to_string());

        let filtered = filter_domains(&data, &domains);
        assert_eq!(filtered.cookie_data.len(), 1);
        assert!(filtered.cookie_data.contains_key(".example.com"));
    }

    #[test]
    fn test_filter_preserves_update_time() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert("github.com".to_string());

        let filtered = filter_domains(&data, &domains);
        assert_eq!(filtered.update_time, data.update_time);
    }

    #[test]
    fn test_filter_no_dot_matches_dot() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert("example.com".to_string());

        let filtered = filter_domains(&data, &domains);
        assert_eq!(filtered.cookie_data.len(), 1);
        assert!(filtered.cookie_data.contains_key(".example.com"));
    }

    #[test]
    fn test_filter_dot_matches_no_dot() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert(".github.com".to_string());

        let filtered = filter_domains(&data, &domains);
        assert_eq!(filtered.cookie_data.len(), 1);
        assert!(filtered.cookie_data.contains_key("github.com"));
    }

    #[test]
    fn test_filter_dot_matches_dot() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert(".example.com".to_string());

        let filtered = filter_domains(&data, &domains);
        assert_eq!(filtered.cookie_data.len(), 1);
        assert!(filtered.cookie_data.contains_key(".example.com"));
    }

    #[test]
    fn test_filter_no_dot_matches_no_dot() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert("github.com".to_string());

        let filtered = filter_domains(&data, &domains);
        assert_eq!(filtered.cookie_data.len(), 1);
        assert!(filtered.cookie_data.contains_key("github.com"));
    }

    #[test]
    fn test_write_netscape_after_filter() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert("github.com".to_string());
        let filtered = filter_domains(&data, &domains);

        let dir = std::env::temp_dir();
        let path = dir.join("test_cookies_filtered.txt");
        write_netscape(&filtered, &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("github.com"));
        assert!(!content.contains("example.com"));
        std::fs::remove_file(&path).unwrap();
    }

    #[test]
    fn test_write_json_after_filter() {
        let data = test_data();
        let mut domains = HashSet::new();
        domains.insert(".example.com".to_string());
        let filtered = filter_domains(&data, &domains);

        let dir = std::env::temp_dir();
        let path = dir.join("test_cookies_filtered.json");
        write_json(&filtered, &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains(".example.com"));
        assert!(!content.contains("github.com"));
        std::fs::remove_file(&path).unwrap();
    }
}
