use std::io::Write;
use std::path::Path;

use crate::decrypt::{CookieData, DecryptedData};

#[derive(Debug)]
pub enum WriteError {
    IoError(std::io::Error),
}

impl std::fmt::Display for WriteError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WriteError::IoError(e) => write!(f, "IO error: {e}"),
        }
    }
}

impl std::error::Error for WriteError {}

impl From<std::io::Error> for WriteError {
    fn from(e: std::io::Error) -> Self {
        WriteError::IoError(e)
    }
}

fn cookie_to_netscape(cookie: &CookieData) -> String {
    let domain = &cookie.domain;
    let include_sub = if domain.starts_with('.') {
        "TRUE"
    } else {
        "FALSE"
    };
    let path = cookie.path.as_deref().unwrap_or("/");
    let secure = if cookie.secure.unwrap_or(false) {
        "TRUE"
    } else {
        "FALSE"
    };
    let expiry = cookie.expiration_date.unwrap_or(0.0) as u64;
    let name = &cookie.name;
    let value = &cookie.value;
    format!("{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
}

pub fn write_netscape(data: &DecryptedData, path: &Path) -> Result<(), WriteError> {
    let mut file = std::fs::File::create(path)?;
    writeln!(file, "# Netscape HTTP Cookie File")?;
    writeln!(file, "# https://curl.se/docs/http-cookies.html")?;
    writeln!(file, "# Generated by cookiecloud-sync")?;

    let mut domains: Vec<&String> = data.cookie_data.keys().collect();
    domains.sort();

    for domain in domains {
        if let Some(cookies) = data.cookie_data.get(domain) {
            for cookie in cookies {
                writeln!(file, "{}", cookie_to_netscape(cookie))?;
            }
        }
    }

    file.flush()?;
    Ok(())
}

pub fn write_json(data: &DecryptedData, path: &Path) -> Result<(), WriteError> {
    let json = serde_json::to_string_pretty(data)
        .map_err(|e| WriteError::IoError(std::io::Error::other(e.to_string())))?;
    std::fs::write(path, &json)?;
    Ok(())
}
